In [1]:
import pandas as pd
from ydata_profiling import ProfileReport


C:\Users\leona\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
trainTitanic = pd.read_csv('train.csv')
trainTitanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
trainTitanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
profile = ProfileReport(trainTitanic, title="Titanic Report")

In [5]:
#profile.to_file("Titanic Report.html")

In [6]:
trainTitanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
trainTitanic.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [8]:
trainTitanic.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [9]:
testTitanic = pd.read_csv('test.csv')
testTitanic.head(5)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [10]:
testTitanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [11]:
testTitanic.isnull().sum().sort_values(ascending=False).head(5)

Cabin     327
Age        86
Fare        1
Name        0
Pclass      0
dtype: int64

In [12]:
trainTitanic.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [13]:
trainTitanic.shape

(891, 12)

In [14]:
trainTitanic.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

In [15]:
trainTitanic = trainTitanic.drop(['Name', 'Ticket', 'Cabin'], axis = 1, errors='ignore')

In [16]:
testTitanic = testTitanic.drop(['Name', 'Ticket', 'Cabin'], axis = 1, errors='ignore')

In [17]:
trainTitanic.Age.mean()

np.float64(29.69911764705882)

In [18]:
trainTitanic.loc[trainTitanic.Age.isnull(), 'Age'] = trainTitanic.Age.mean()

In [19]:
testTitanic.loc[testTitanic.Age.isnull(), 'Age'] = testTitanic.Age.mean()

In [20]:
trainTitanic.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [21]:
trainTitanic.Embarked.mode()

0    S
Name: Embarked, dtype: object

In [22]:
trainTitanic.Embarked.mode()[0]

'S'

In [23]:
trainTitanic.loc[trainTitanic.Embarked.isnull(), 'Embarked'] = trainTitanic.Embarked.mode()[0]

In [24]:
testTitanic.loc[testTitanic.Fare.isnull(), 'Fare'] = testTitanic.Fare.mean()

In [25]:
testTitanic.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

In [26]:
trainTitanic.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [27]:
trainTitanic = pd.get_dummies(trainTitanic, columns=['Sex', 'Embarked'], drop_first=True)
testTitanic = pd.get_dummies(testTitanic, columns=['Sex', 'Embarked'], drop_first=True)

In [28]:
trainTitanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex_male          bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [29]:
trainTitanic.columns[trainTitanic.dtypes != 'object']

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'Sex_male', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [30]:
trainTitanic_nr = trainTitanic.loc[:,trainTitanic.columns[trainTitanic.dtypes != 'object']]

In [31]:
trainTitanic_nr.head(5)

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  \
0            1         0       3  22.0      1      0   7.2500      True   
1            2         1       1  38.0      1      0  71.2833     False   
2            3         1       3  26.0      0      0   7.9250     False   
3            4         1       1  35.0      1      0  53.1000     False   
4            5         0       3  35.0      0      0   8.0500      True   

   Embarked_Q  Embarked_S  
0       False        True  
1       False       False  
2       False        True  
3       False        True  
4       False        True

In [32]:
testTitanic_col = testTitanic.columns[testTitanic.dtypes != 'object']
testTitanic_col

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [33]:
testTitanic_nr = testTitanic.loc[:,testTitanic_col]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X = trainTitanic.drop(['PassengerId', 'Survived'], axis=1)
y = trainTitanic.Survived

In [36]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
from sklearn import tree

In [41]:
clf_ac = tree.DecisionTreeClassifier(random_state=42)

In [42]:
clf_ac = clf.fit(X_train, y_train)

In [43]:
y_pred_ac = clf.predict(X_val)

In [62]:
from sklearn.neighbors import KNeighborsClassifier

In [63]:
clf_knn = KNeighborsClassifier(n_neighbors=3)

In [64]:
clf_knn = clf_knn.fit(X_train, y_train)

In [65]:
y_pred_knn = clf.predict(X_val)

In [66]:
from sklearn.linear_model import LogisticRegression

In [67]:
clf_rl = LogisticRegression(random_state=42).fit(X, y)

C:\Users\leona\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [68]:
clf_rl = clf_rl.fit(X_train, y_train)

In [69]:
y_pred_rl = clf.predict(X_val)

In [70]:
from sklearn.metrics import accuracy_score

In [71]:
accuracy_score(y_val, y_pred_ac)

0.7423728813559322

In [72]:
accuracy_score(y_val, y_pred_knn)

0.7423728813559322

In [73]:
accuracy_score(y_val, y_pred_rl)

0.7423728813559322

In [74]:
from sklearn.metrics import confusion_matrix

In [75]:
confusion_matrix(y_val, y_pred_ac)

array([[137,  38],
       [ 38,  82]])

In [76]:
confusion_matrix(y_val, y_pred_knn)

array([[137,  38],
       [ 38,  82]])

In [77]:
confusion_matrix(y_val, y_pred_rl)

array([[137,  38],
       [ 38,  82]])

In [79]:
X_train.head(3)

Pclass        Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  \
6         1  54.000000      0      0  51.8625      True       False   
718       3  29.699118      0      0  15.5000      True        True   
685       2  25.000000      1      2  41.5792      True       False   

     Embarked_S  
6          True  
718       False  
685       False

In [80]:
testTitanic_nr.head(3)

PassengerId  Pclass   Age  SibSp  Parch    Fare  Sex_male  Embarked_Q  \
0          892       3  34.5      0      0  7.8292      True        True   
1          893       3  47.0      1      0  7.0000     False       False   
2          894       2  62.0      0      0  9.6875      True        True   

   Embarked_S  
0       False  
1        True  
2       False

In [81]:
x_test = testTitanic_nr.drop('PassengerId', axis=1)

In [84]:
y_pred = clf_rl.predict(x_test)

In [85]:
testTitanic['Survived'] = y_pred

In [88]:
base_envio = testTitanic[['PassengerId', 'Survived']]

In [90]:
base_envio.to_csv('result_titanic', index=False)